; #########################################################################
;
;   game.inc - Includes for EECS205 Assignment 4/5
;
;
; #########################################################################

;; Library Definitions
MouseInfo STRUCT
 horiz DWORD ?
 vert  DWORD ?
 buttons DWORD ?
MouseInfo ENDS

MK_CONTROL  = 0008h  ;; The CTRL key is down.
MK_LBUTTON  = 0001h  ;; The left mouse button is down.
MK_MBUTTON  = 0010h  ;; The middle mouse button is down.
MK_RBUTTON  = 0002h  ;; The right mouse button is down.
MK_SHIFT    = 0004h  ;; The SHIFT key is down.
MK_XBUTTON1 = 0020h  ;; The first X button is down.
MK_XBUTTON2 = 0040h  ;; The second X button is down.

_EECS205SPRITE STRUCT
 fxptXCenter    FXPT    ?
 fxptYCenter    FXPT    ?
 ptrBitmap      DWORD   ?
 ptrRect        DWORD   ?
 speed          FXPT    ?
 active         DWORD   0
_EECS205SPRITE ENDS

EECS205SPRITE TYPEDEF _EECS205SPRITE

;; Library Functions
BlackStarField	PROTO
DrawStr PROTO myStr:PTR BYTE, x:DWORD, y:DWORD, color:DWORD

;; Library Data
EXTERNDEF StarBitmap:EECS205BITMAP
EXTERNDEF MouseStatus:MouseInfo
EXTERNDEF KeyUp:DWORD
EXTERNDEF KeyDown:DWORD
EXTERNDEF KeyPress:DWORD


EXTERNDEF jayz_head:EECS205BITMAP
EXTERNDEF kanye_head:EECS205BITMAP
EXTERNDEF player:EECS205BITMAP
EXTERNDEF zone:EECS205BITMAP


;; User Defined Functions
GameInit PROTO
GamePlay PROTO
UpdatePlayerPos PROTO STDCALL ptrSprite:PTR EECS205SPRITE
UpdateEnemyPos PROTO STDCALL ptrSprite:PTR EECS205SPRITE
UpdateRect PROTO STDCALL ptrSprite:PTR EECS205SPRITE
ActivateEnemy PROTO STDCALL ptrSprite:PTR EECS205SPRITE, index:DWORD
RandX PROTO
RandY Proto






